# Site settings
course_name: "6.S183: A Practical Introduction to Diffusion Models"
course_description: "Diffusion models are a class of generative models that iteratively refine noise into structured data. Although initially developed for image generation, they have been successful in many other domains such as robotics and molecular design. In this course we will introduce the basics of diffusion models and demonstrate how to build them from the ground up, culminating in a simple but powerful library to train diffusion models on custom data, as well as using state-of-the-art pretrained models for a variety of downstream tasks.

<p> This is an introductory course targeted at students and researchers who wish to learn about diffusion models and explore their applications to new domains, or those currently working with diffusion models and want to understand how to effectively modify and adapt them for their specific applications."
course_semester: "IAP 2025"

meta_title: "A practical introduction to diffusion models"
meta_description: "Course website for the MIT IAP 2025 class: 6.S183 A Practical Introduction to Diffusion Models -- From Algorithms to Implementation"
meta_image: "_images/site_screenshot.png"
meta_url: "https://www.practical-diffusion.org/"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.practical-diffusion.org" # the base hostname & protocol for your site

schoolname: "MIT EECS"
schoolurl: "https://www.practical-diffusion.org"
twitter_username:

address: |


# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-S9PL2XSY3D

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"
timezone: EST

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
